language: python
install: 
- stage: test
  script:
  - pip install -e .[tests]
before_script:
  - pip install python-coveralls
  - pip install pytest-cover
script: 
  - py.test tests/ 
after_success:
  - coveralls